### ISSUE TITLE
Создание DiseaseList

### ISSUE THREAD

**Issue by Bakkayaroy** [KirillSN1/Senome-Morok#5]
Содержит в себе метод list
Который возвращает конструкцию типа

> new DiseasModel{
> id=1,name="name"....
> },
> new Diseasmodel{
> id=2,name="name2"
> }; 

и т.к далее, сделай 3-4 болезни

**Comment by artem1101gavrilov** [comment]
https://github.com/KirillSN1/Senome-Morok/blob/feature/disease/Assets/Scripts/Desiase/Desiase.cs
