### ISSUE TITLE
Уменьшение кол-во хп из-за болезни

### ISSUE THREAD

**Issue by Bakkayaroy** [KirillSN1/Senome-Morok#7]
В update проверка, на то, что diseaseList содержит хотя бы один элемент
Если содержит, то вызвать метод

В методе перебираем все болезни и отнимаем хп

> foreach(var disease in diseaseList)
> {
> HealPoint -=disease.diseaseSpeed*Time.fixedDeltaTime;
> }

**Comment by artem1101gavrilov** [comment]
А может не в Update, а например в InvokeRepeating?

**Comment by Bakkayaroy** [comment]
> А может не в Update, а например в InvokeRepeating?
Да, надо будет переделать, ты прав
